### ISSUE TITLE
Logging plan of attack

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#1649]
## Outstanding Issues
- [ ] [Make the NServiceBus info logging opt-in](https://github.com/Particular/NServiceBus/issues/598)
- [ ] [Provide sensible loglevels for dependencies](https://github.com/Particular/NServiceBus/issues/1436)
- [x] [ProfileManager logger is initialised to NullLogger before custom loggerfactory is set up](https://github.com/Particular/NServiceBus/issues/1506)
- [x] [Setting Logging library should be done before calling Configure.With](https://github.com/Particular/NServiceBus/issues/1484)
