### ISSUE TITLE
Remaining static fields

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2290]
* [x] Address.Undefined
* [x] Address.Self
* [x] Address.defaultMachine
* [x] Address.preventChanges
* [x] Address.ignoreMachineName
* [x] Configure.instance
* [x] DataBusReceiveBehavior.cache https://github.com/Particular/NServiceBus/issues/2381
* [x] DataBusSendBehavior.cache https://github.com/Particular/NServiceBus/issues/2381
* [x] ExtensionMethods.SetHeaderAction
* [x] ExtensionMethods.GetHeaderAction
* [ ] ~~ExtensionMethods.currentMessageBeingHandled~~ ThreadStatic
* [x] Unicast.UnicastBus.HostIdForTransportMessageBecauseEverythingIsStaticsInTheConstructor
* [x] Features.Sagas.SagaEntityToMessageToPropertyLookup https://github.com/Particular/NServiceBus/issues/2378
* [x] Features.Sagas.MessageTypeToSagaTypesLookup https://github.com/Particular/NServiceBus/issues/2378
* [x] Features.Sagas.SagaEntityTypeToSagaTypeLookup https://github.com/Particular/NServiceBus/issues/2378
* [x] Features.Sagas.SagaTypeToSagaEntityTypeLookup https://github.com/Particular/NServiceBus/issues/2378
* [x] Features.Sagas.FinderTypeToSagaEntityTypeLookup https://github.com/Particular/NServiceBus/issues/2378
* [x] Features.Sagas.FinderTypeToMessageToMethodInfoLookup https://github.com/Particular/NServiceBus/issues/2378
* [x] Features.Sagas.SagaTypeToMessageTypesRequiringSagaStartLookup
* [x] Features.Sagas.SagaMessageFindingConfiguration https://github.com/Particular/NServiceBus/issues/2378
* [ ] ~~MsmqUtilities.localIp~~ this caches the local machine ip address which does not change
* [x] Encryption.EncryptionMutator.cache (Since this is purely reflection based with no config interaction it can be ignored)
* [x] SecondLevelRetries.DefaultRetryPolicy.NumberOfRetries https://github.com/Particular/NServiceBus/issues/2374
* [x] SecondLevelRetries.DefaultRetryPolicy.TimeIncrease https://github.com/Particular/NServiceBus/issues/2374
* [x] SecondLevelRetries.DefaultRetryPolicy.RetryPolicy https://github.com/Particular/NServiceBus/issues/2375
* [x] MessageInterfaces.MessageMapper.Reflection.MessageMapper.SUFFIX
* [x] MessageInterfaces.MessageMapper.Reflection.MessageMapper.interfaceToConcreteTypeMapping
* [x] MessageInterfaces.MessageMapper.Reflection.MessageMapper.concreteToInterfaceTypeMapping
* [x] MessageInterfaces.MessageMapper.Reflection.MessageMapper.nameToType
* [x] MessageInterfaces.MessageMapper.Reflection.MessageMapper.typeToConstructor
* [x] ObjectBuilder.Common.CommonObjectBuilder.sync https://github.com/Particular/NServiceBus/issues/2376
* [x] Serializers.XML.XmlMessageSerializer.typeToProperties
* [x] Serializers.XML.XmlMessageSerializer.typeToFields
* [x] Serializers.XML.XmlMessageSerializer.typesToCreateForArrays
* [x] Serializers.XML.XmlMessageSerializer.typesToCreateForEnumerables
* [x] Serializers.XML.XmlMessageSerializer.typesBeingInitialized
* [ ] ~~Serializers.XML.XmlMessageSerializer.defaultNameSpace~~ ThreadStatic
* [ ] ~~Serializers.XML.XmlMessageSerializer.prefixesToNamespaces~~ ThreadStatic
* [ ] ~~Serializers.XML.XmlMessageSerializer.messageBaseTypes~~ ThreadStatic
* [ ] ~~Serializers.XML.XmlMessageSerializer.namespacesToAdd~~ ThreadStatic
* [ ] ~~Callback.AsyncControllerType~~ not an issue since this is per machine
* [x] Unicast.HandlerInvocationCache.HandlerCache
* [x] Unicast.HandlerInvocationCache.TimeoutCache
* [ ] ~~Unicast.Transport.TransportReceiver.needToAbort~~ ThreadStatic
* [x] CircuitBreakers.RepeatedFailuresOverTimeCircuitBreaker.NoPeriodicTriggering

Since the below are purely reflection based with no config interaction they can be ignored
* [x] Utils.Reflection.DelegateFactory.PropertyInfoToLateBoundProperty
* [x] Utils.Reflection.DelegateFactory.FieldInfoToLateBoundField
* [x] Utils.Reflection.DelegateFactory.PropertyInfoToLateBoundPropertySet
* [x] Utils.Reflection.DelegateFactory.FieldInfoToLateBoundFieldSet
* [x] Utils.Reflection.ExtensionMethods.IsSystemTypeCache
* [x] Utils.Reflection.ExtensionMethods.TypeToNameLookup

**Comment by SimonCropp** [comment]
@andreasohlund the address ones

**Comment by andreasohlund** [comment]
Since we have plans to fix the address should we:

1. Close this one since it will be covered the address refactoring you
started @simoncropp
2. Open a new issue for the address fields
3. Leave this as is

Thoughts?

**Comment by SimonCropp** [comment]
finished in the develop branch.
