### ISSUE TITLE
Refactor DeterministicGuid.Create to use a managed MD5 implementation

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus#3349]
While that might not be popular to roll out your own crypto, I think we should replace the MD5 algorithm based on Windows Crypto Service Provider with a purely managed implementation.
### Pros
- Easier route to .NET Core
- FIPS validation will not trigger an error on this (which is OK, because we don't use MD5 for security here)
- Possibly better performance for small payloads
### Cons
- We need to test extensively for backwards compatibility
### TODO
- [ ] Look for a quality managed MD5 implementation
- [ ] ... or roll our own
- [ ] Test extensively for compatibility: official test vectors + fuzzing
- [ ] Raise similar issues is downstream repos that use MD5

**Comment by danielmarbach** [comment]
@MarcinHoppe we should check if we touch the cryptop parts that we optionally use a FIPS compliant algorithm https://github.com/Particular/NServiceBus/issues/1217

**Comment by mauroservienti** [comment]
In light of FIPS I'd rather prefer to leave the current implementation as is and refactor to allow the user to replace entirely the implementation, less potential bugs, zero work to test wire compatibility.

**Comment by SimonCropp** [comment]
@mauroservienti what do u propose for .netcore?

**Comment by mauroservienti** [comment]
good question @SimonCropp, if .NET Core must be wire and backward compatible with previous version than all what we can do is what @MarcinHoppe suggest, I see no way around it.

**Comment by MarcinHoppe** [comment]
@danielmarbach Thanks. If we reach conclusion that we want to do it, then the plan of attack will need to include PRs in downstream repos (Raven and Gateway).

@mauroservienti The problem we are trying to solve is that MD5 is not used for security here and triggers FIPS validation error for no good reason. The proposal will make it easy for people who do not use NSB security features to go FIPS compliant if they need it. If someone needs NSB security features and need them to be FIPS compliant, then they can drop in their own implementation of crypto functions.

Does this make sense?

**Comment by mauroservienti** [comment]
@MarcinHoppe yes, it makes a lot of sense. My point is that if we don't take into account .NETCore replacing MD5 adds no value at all to all the existing users and at the same time is a large effort on our side to guarantee wire compatibility. If we want to target .NETCore and FIPS than it makes a lot of sense. It makes a lot of sense if we need to support a FIPS environment that talks to a non-FIPS one that is running on a previous version.

**Comment by MarcinHoppe** [comment]
@Particular/nservicebus-maintainers It seems we have a consensus that it would be good to have this done. Do we need to have this in first release of v6? My take on it is a no, but would like more people to voice their opinion, especially if there's something I don't see that would make this a v6 candidate.

**Comment by timbussmann** [comment]
so is this considered a feature or a refactoring?

@MarcinHoppe I'd say prioritization is the @Particular/platform-dev-squad task.

**Comment by mauroservienti** [comment]
to me is a refactoring that is part of the .NETCore effort, and
enables FIPS as well.

On Wed, Jan 27, 2016 at 8:25 AM Tim Bussmann <notifications@github.com>
wrote:

> so is this considered a feature or a refactoring?
>
> @MarcinHoppe <https://github.com/MarcinHoppe> I'd say prioritization is
> the @Particular/platform-dev-squad
> <https://github.com/orgs/Particular/teams/platform-dev-squad> task.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/issues/3349#issuecomment-175462090>
> .
>
-- 
Mauro Servienti | Solution Architect | Particular Software

**Comment by MarcinHoppe** [comment]
@timbussmann This definitely falls under refactoring but opens new doors for us in the future (.NET Core & FIPS).

**Comment by adamralph** [comment]
Is there any external net effect of the change? E.g. is something more secure as a result?

**Comment by danielmarbach** [comment]
@adamralph see PROs in the description

**Comment by adamralph** [comment]
The only "pro" I don't understand is:

* FIPS validation will not trigger an error on this (which is OK, because we don't use MD5 for security here)

For context, I'm trying to answer @timbussmann's question:

> so is this considered a feature or a refactoring?

But I probably don't need to be doing so, it's just because he pinged the squad about something else in the same comment. :smile:

**Comment by MarcinHoppe** [comment]
@adamralph We use MD5 in the core to create a fingerprint of some data. We could use any hash function here for this, the calculation does not require a crypto hash function with all its properties like pre-image and collision resistance.

The problem is that when we run NSB on Windows with FIPS mode on then the framework throws an exception when `MD5CryptoServiceProvider` is used, because MD5 is not FIPS-compliant. This, in my mind, is not necessary.

This task is to provide bit-for-bit compatibility with fingerprints generated by `MD5CryptoServiceProvider` and not offend the FIPS mode.

Does this make sense?

**Comment by adamralph** [comment]
@MarcinHoppe thanks for the explanation. Yes, that does make sense.

So, effectively, we have a bug? Since users running Windows with FIPS mode get an exception thrown for no good reason?

**Comment by timbussmann** [comment]
@adamralph we do not support FIPS mode (see https://github.com/Particular/NServiceBus/issues/1217#issuecomment-141098744)

**Comment by danielmarbach** [comment]
This would be a feature. Not a bug. I think we need to mark it as such.

**Comment by adamralph** [comment]
@timbussmann ah, I see.

@danielmarbach agreed. New feature: Support FIPS

**Comment by danielmarbach** [comment]
@adamralph Expect that we would never call it Support FIPS. We do not want to officially state that. If it happens to be FIPS compliant than OK. But we'd never publicly announce that we do.

**Comment by adamralph** [comment]
@danielmarbach I must admit I don't even know what it is. :stuck_out_tongue_closed_eyes:

Anyway, I'll leave it to the core team to decide what to call the feature :wink:

**Comment by MarcinHoppe** [comment]
@adamralph @timbussmann @danielmarbach I think there is a consensus that we don't ever want to state we support FIPS. What we want to achieve here is to remove NSB as a blocker towards FIPS compliance. Currently it will prevent running in FIPS mode even if users provide their own `IEncryptionService` that is FIPS compliant.

With regards to classification, I'd err on the side of this being a new feature. It is also clearly a refactoring (we change internal structure of the code without changing its external behaviour).

**Comment by adamralph** [comment]
> It is also clearly a refactoring (we change internal structure of the code without changing its external behaviour).

For me, refactoring is part of nearly every single feature (and many bug fixes) so I don't think there's any need to call this out with a label.

**Comment by adamralph** [comment]
I only use the "Type: Refactoring" label for something which is *purely* a refactoring, with no other purpose.

**Comment by timbussmann** [comment]
> I only use the "Type: Refactoring" label for something which is purely a refactoring, with no other purpose.

@adamralph Then I don't see any value in that label. There is no reason for an issue about a refactoring if there is no impact at all. In that case a simple PR will suffice, no label required.

Let's not derail this issue. If you disagree with the way we currently use the existing labels, feel free to raise a discussion somewhere.

**Comment by danielmarbach** [comment]
https://github.com/Particular/PlatformDevelopment/blob/master/IssueLabels.md#type-refactoring

> This issue is a refactoring/internal change that isn't relevant for the end users. It will not be included in release notes or release announcements

So the real question is: Should this go into the release announcement if we build it. If the answer is YES, it has to be labeled as a feature. if the answer is NO it has to be labeled as a refactoring. 

Any discussions which are generic about the meaning of a label should happen as issues or proposal PRs on platform dev

https://github.com/Particular/PlatformDevelopment/blob/master/IssueLabels.md#type-refactoring

**Comment by andreasohlund** [comment]
This is required for netstandard support. The 2 usages we have currently:

* Creating the [default HostId passed to SC](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Hosting/HostInformationFeature.cs#L20) `s.SetDefault(HostIdSettingsKey, DeterministicGuid.Create(fullPathToStartingExe, RuntimeEnvironment.MachineName));`
* Creating a [guid HostId when users specify the instance and host names](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Hosting/HostInfoSettings.cs#L56) (used mainly for azure) `config.Settings.Set(HostInformationFeature.HostIdSettingsKey, DeterministicGuid.Create(instanceName, hostName));`

Would a new algorithm create the same guid?

if yes: 👍 

if no: We have to deal with the HostId in some way

**Comment by MarcinHoppe** [comment]
A lot has changed since this issue has been created. Maybe netstandard supports MD5 now?

**Comment by timbussmann** [comment]
the [standard 2.0 api](https://raw.githubusercontent.com/dotnet/standard/master/docs/versions/netstandard2.0_ref.md) at least seems to contain `MD5CryptoServiceProvider`. We haven't defined which standard we target yet.

**Comment by adamralph** [comment]
Targeting .NET Standard 2.x will be much easier than 1.x for many reasons. I don't think the cost of supporting .NET Standard 1.x will be worth it. The only benefit will be support for .NET Core 1.x, but IMHO that's a tyre fire and we should aim for .NET Core 2.x (via .NET Standard 2.x).

**Comment by bording** [comment]
FYI, the best way to determine if something is supported, and what version it's supported in, is to use https://apisof.net/ to look it up.

For example, here's MD5CryptoServiceProvider: https://apisof.net/catalog/System.Security.Cryptography.MD5CryptoServiceProvider

As @timbussmann said, it has been added to .NET Core 2.0 and .NET Standard 2.0.

**Comment by andreasohlund** [comment]
Given that we'll target netstandard2.0 this seems to be a non issue then, should we close this?

**Comment by andreasohlund** [comment]
Closing this since we'll target .NET Standard 2.0
